.class public final Lccsankotlinx/android/parcel/Parceler$DefaultImpls;
.super Ljava/lang/Object;
.source "Parceler.kt"


# annotations
.annotation system Ldalvik/annotation/EnclosingClass;
    value = Lccsankotlinx/android/parcel/Parceler;
.end annotation

.annotation system Ldalvik/annotation/InnerClass;
    accessFlags = 0x19
    name = "DefaultImpls"
.end annotation

.annotation runtime Lccsankotlin/Metadata;
    k = 0x3
    mv = {
        0x1,
        0x5,
        0x1
    }
    xi = 0x30
.end annotation


# direct methods
.method public static newArray(Lccsankotlinx/android/parcel/Parceler;I)[Ljava/lang/Object;
    .locals 2
    .param p0, "this"    # Lccsankotlinx/android/parcel/Parceler;
    .param p1, "size"    # I
    .annotation system Ldalvik/annotation/Signature;
        value = {
            "<T:",
            "Ljava/lang/Object;",
            ">(",
            "Lccsankotlinx/android/parcel/Parceler<",
            "TT;>;I)[TT;"
        }
    .end annotation

    const-string v0, "this"

    invoke-static {p0, v0}, Lccsankotlin/jvm/internal/Intrinsics;->checkNotNullParameter(Ljava/lang/Object;Ljava/lang/String;)V

    .line 41
    new-instance v0, Lccsankotlin/NotImplementedError;

    const-string v1, "Generated by Android Extensions automatically"

    invoke-direct {v0, v1}, Lccsankotlin/NotImplementedError;-><init>(Ljava/lang/String;)V

    throw v0
.end method
